### ISSUE TITLE
Head drop and Display name

### ISSUE THREAD

**Issue by ghost** [GenDeathrow/PlayerRaiders#19]
Im only assuming that your mod allows for player head drops, because I killed a Raider and got a head drop. this is the problem...

To avoid confusion between Raider kills and player kills I added the word 'Raider' to the names in the config file.  This means that when the head drops its trying to download the head for 'Raider Crimson_Fluff' instead of Gamertag 'Crimson_Fluff'

Could you add a displayname or a gamertag line to the config files?  actually thinking about it download the head using the player skin name? cos that should always match the gamertag I would have thought?

also maybe cut down the spam in chat?

Thanks, loving the Idea of this mod.

**Comment by GenDeathrow** [comment]
I guess I could, id have to see about doing that cause I would have to change some of how the system works. But the whole point of raiders was to mimic players to an extent for the mod pack Invasion. I'll look into, but no promises at the moment. 

Also I do not spam the chat. There is another mod that will spam chat ,because raiders have custom names. I cant remember what mod it is. but you can disable it via configs of that mod. I think Quark has it.. but there are other mods too.

**Comment by GenDeathrow** [comment]
Vanilla skull code will not support this feature. It means I'll have to write my own code to support this. And right now, I just wont have the time. So for now, if your using custom skins, than player heads just will not drop. 

Did you ever find the mod spamming your chat with death messages? If you have "cofh core", I would check their code. If I change my side right now, I will break a lot of code.  I think they have a setting for "Death Messages".

**Comment by ghost** [comment]
So we wanted to have our patrons as raiders. And we have about 20+ patrons and everytime they kill each other its reported in the chat.  I'll have a look at cofh core see if theres a config i can change.

Thanks again



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by ghost** [comment]
it was the COFH mod spamming chat, ive turned off Entity Death Messages.  It would be good to have custom display names and have the heads drop work - but thank you for your time, its a great mod and adds a good challenge to minecraft - look forward to future updates
