### ISSUE TITLE
Game breaking Crash during melee with Zygon

### ISSUE THREAD

**Issue by Hiddenisme** [GenDeathrow/PlayerRaiders#25]
Im in the process of making a new modpack and welp. I used the communicator to call down rebels to tet the skins i gave them aswell as their combat capability against some Zygons from the Dalek Mod. ranged fighting worked until the zygon got close enough for melee damage to the raider.

https://pastebin.com/9pVL5m2m

I did some testign to see if Zygons alone would break the map upon melee with me and no crash. Only when the melee a raider does the crash happen. Seeing as the first line in the crash report mentions Raiders I post here first.

> java.lang.ClassCastException: com.gendeathrow.pmobs.entity.mob.EntityRanger cannot be cast to net.minecraft.entity.player.EntityPlayer
> 	at com.swdteam.common.entity.EntityZygon.func_70652_k(EntityZygon.java:62)
> 	at net.minecraft.entity.ai.EntityAIAttackMelee.func_190102_a(EntityAIAttackMelee.java:178)

My current mod list looks like this:
![image](https://user-images.githubusercontent.com/1483674/47188140-6b625c80-d2fc-11e8-8c29-98b5956a469b.png)

**Comment by Hiddenisme** [comment]
**Update:** Seems its just the Zygons at the moment... hmmmmm

**Comment by GenDeathrow** [comment]
Thats cause the Zygons are casting them as a players when they aren't. This is actually an issue with the darlek mod. I'm not sure why they are attempted to cast them as players, but they are.  You will want to report this to them. As I don't think their code is public for me to look at easily.

 Im closing this cause there is nothing I  can do from my side atm. 

Edit I mean you were right to try and post to me since you saw my mod, but if you look normally past that part it will say this.

`at com.swdteam.common.entity.EntityZygon.func_70652_k(EntityZygon.java:62)`

This normally shows where the crash actually happened at. Hope that helps

**Comment by Hiddenisme** [comment]
It does. I definitely looked passed it being your mod's fault. I continued to test Rebels in many other combat situations with Dalek mod and fount that so far only the freaking Zygons break. Your mod is only mentioned in the first line of the crash report, every else its Zygon this and that. 

Thanks for your time any way.

PS could i out fit your guys with guns from Techguns? and will they use them?

**Comment by GenDeathrow** [comment]
No not really, I have been trying to come up with an idea to implement ranged weapons uses. Atm I dont have anything that works well other than the hardcoded creeper mod with lasers. When I get the chance I will look into implementing a feature like this.
