### ISSUE TITLE
customSkin config not displaying skins

### ISSUE THREAD

**Issue by Memebassador** [GenDeathrow/PlayerRaiders#32]
I'm not sure if it is a bug or I'm just failing to properly modify the config file, but I cannot for the life of me get the customSkin module of raider_skins to work for me.

Here is an image of the raider_skins JSON file:
![raiders_skins](https://user-images.githubusercontent.com/51892608/59571292-ebe28400-9068-11e9-9da0-2cff30d3050c.jpg)

And here are the three skins I am trying to implement (subject to change):
![raider](https://user-images.githubusercontent.com/51892608/59571316-13d1e780-9069-11e9-9be1-060d114dcb61.png)
![mutant](https://user-images.githubusercontent.com/51892608/59571320-159bab00-9069-11e9-9f07-14cd8806c989.png)
![cultist](https://user-images.githubusercontent.com/51892608/59571325-16ccd800-9069-11e9-8201-e73698e77ca8.png)

And finally a game screenshot:
![2019-06-16_19 03 00](https://user-images.githubusercontent.com/51892608/59571370-72976100-9069-11e9-82cd-f8708000c808.png)

I should note that I am using a bunch of mods as well. I did see that there was a previous issue regarding the Cyberware mod, which is installed. Besides the Cyberzombies from that mod, though, no other mods add their own custom mobs (although Lycanite's Mobs is a likely future addition). Thanks in advance.

**Comment by GenDeathrow** [comment]
I see if I can check this later, skins all look good. and it seems like the config is right. but I will see what I can do.

**Comment by Memebassador** [comment]
Thanks again.

**Comment by GenDeathrow** [comment]
So was trying to figure this out.. noticed you have enabled set to false. Have you set them to true to turn that skin on?

**Comment by GenDeathrow** [comment]
Sorry for late response.. just have alot going on at the moment

**Comment by Memebassador** [comment]
Hi, no problem at all. It's been a while since I used the mod last but if I remember correctly, I set that to false because I figured it might be trying to use skins from online that don't actually exist. I believe when I had that set to true, skins were just white with the overlays. I'll let you know in a little while if that's still the case.

**Comment by Memebassador** [comment]
![image](https://user-images.githubusercontent.com/51892608/60626130-67556c80-9daf-11e9-833a-963c7b3bc126.png)

It did detect the skin but it is not displaying correctly now. Also, I'll be honest, I'm trying to make a modpack and I've since changed a good amount about it, namely by adding my own raiders with MCreator (I know, ew). Anyways, I would still love to use your mod, but I was wondering if it would be possible to give **one kind** of raider **only one** skin, and if it would be possible to change the sounds the raider makes with ResourceLoader or just a resource pack.

**Comment by GenDeathrow** [comment]
So I forgot skins still don't work with older styles. but the skin I attached here is the Proper size that works. It has seem to work only with Alex skin sizes. I may have to see about changing that and actually determining what size the image is and adjust accordingly. As for getting the older skin sizes working I will look into but determining that can sucks. I may have to have a value in the configs you set instead of me auto figuring it out.  If you wanted possibly a skin override per class I may be able to append something like that on for the configs.  I haven't had time to make updates as of late.. but may have some free time tomorrow to take a look at the code. 

If you wanted to just set a single skin than you can just do that with the current system. Set them all to the same custom skin. 


![raider](https://user-images.githubusercontent.com/3720710/60758865-dadec000-9fe1-11e9-88f5-a54a299746d3.png)

** Also I kinda made that skin quick and dirty, So you may need to tweak it some. I could be off by a pixel or two.

**Comment by Memebassador** [comment]
Alright, thanks for your help. Also, a skin override would be amazing for what I'm working on, but don't lose sleep over getting a feature like that taken care of. Any way to change sounds, though? Don't mean to be a nuisance with all the questions, just wondering.

Thanks again regardless, I appreciate your help.

**Comment by GenDeathrow** [comment]
Technically you can change sounds with a resource pack. But I haven't ever messed with that.

**Comment by GenDeathrow** [comment]
Ok so I have set it up to yell at ppl when the incorrect image size is used. its easier for now instead of trying to set up the use of old skin images.  Im going to close this for now.. if you message me I can still respond.

**Comment by Memebassador** [comment]
Thanks for the help!
